
const restaurants = [
    {city:"vancouver",
     name:"Savio Volpe",
     img:"./images/restaurant1.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"calgary",
     name:"Bonterra Trattoria",
     img:"./images/restaurant2.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"winnipeg",
     name:"Chop SteakHouse",
     img:"./images/restaurant3.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"toronto",
     name:"Grey Gardens",
     img:"./images/restaurant4.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"montreal",
     name:"Sandwicherie Sue",
     img:"./images/restaurant5.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"vancouver",
     name:"Botanist",
     img:"./images/restaurant6.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"calgary",
     name:"cassis Bistro",
     img:"./images/restaurant7.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"winnipeg",
     name:"Peasant Cookery",
     img:"./images/restaurant8.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"toronto",
     name:"Pinky's Ca Phe",
     img:"./images/restaurant2.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
    {city:"montreal",
     name:"Moccione",
     img:"./images/restaurant4.jpg",
     desc:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi maxime omnis a saepe quo blanditiis quis dignissimos eum quia officia.",
    },
]

export default restaurants;